// Centralized icon exports (react-icons)
import {
  FaChartLine,
  FaHouse,
  FaPenNib,
  FaLayerGroup,
  FaArrowLeft,
  FaAngleRight,
  FaArrowRight,
  FaUser,
  FaBox,
  FaBagShopping,
  FaDollarSign,
  FaClock,
  FaPlus,
  FaRotateRight,
  FaPenToSquare,
  FaTrashCan,
  FaCloudArrowUp,
  FaCloudArrowDown,
  FaNewspaper,
  FaTag,
  FaMagnifyingGlass,
  FaSliders,
  FaMapLocationDot,
  FaArrowRightLong,
  FaArrowLeftLong,
  FaRulerCombined,
  FaLocationDot,
  FaShieldHeart,
  FaBookOpenReader,
  FaBookmark,
  FaRegBookmark,
  FaCircleInfo,
  FaCheck,
  FaCircleExclamation
} from "react-icons/fa6";

export const Icons = {
  Dashboard: FaChartLine,
  Room: FaHouse,
  Post: FaPenNib,
  Category: FaLayerGroup,
  Back: FaArrowLeft,
  NextChevron: FaAngleRight,
  ArrowRight: FaArrowRight,
  User: FaUser,
  Box: FaBox,
  Order: FaBagShopping,
  Money: FaDollarSign,
  Clock: FaClock,
  Plus: FaPlus,
  Refresh: FaRotateRight,
  Edit: FaPenToSquare,
  Trash: FaTrashCan,
  Publish: FaCloudArrowUp,
  Unpublish: FaCloudArrowDown,
  Newspaper: FaNewspaper,
  Tag: FaTag,
  Search: FaMagnifyingGlass,
  Filters: FaSliders,
  Map: FaMapLocationDot,
  ArrowRightLong: FaArrowRightLong,
  ArrowLeftLong: FaArrowLeftLong,
  Ruler: FaRulerCombined,
  Pin: FaLocationDot,
  Verified: FaShieldHeart,
  Reader: FaBookOpenReader,
  Bookmark: FaBookmark,
  BookmarkOutline: FaRegBookmark,
  Info: FaCircleInfo,
  Check: FaCheck,
  Alert: FaCircleExclamation
};

